//! Static word lists: no initialisation, no heap, no hashing.
//!
//! Generated by build.rs from the dictionary files. A list is a sorted blob plus an offset
//! table; lookup is a binary search that compares in place, lower-casing the query on the fly.
//! (The old `LazyLock<HashSet>` rebuilt 24k entries on the first keystroke and allocated a
//! `String` per lookup.)

use std::cmp::Ordering;

pub struct WordList {
    blob: &'static [u8],
    idx: &'static [u8],
    /// first entry not smaller than each pair of first letters (676 + 1 little-endian u32)
    bkt: &'static [u8],
}

macro_rules! list {
    ($name:literal) => {
        WordList {
            blob: include_bytes!(concat!(env!("OUT_DIR"), "/", $name, ".blob")),
            idx: include_bytes!(concat!(env!("OUT_DIR"), "/", $name, ".idx")),
            bkt: include_bytes!(concat!(env!("OUT_DIR"), "/", $name, ".bkt")),
        }
    };
}

/// English words (auto-restore); consulted only at word boundaries by the restore logic.
pub static EN: WordList = list!("en");
/// Vietnamese syllables.
pub static VI: WordList = list!("vi");
/// Words that must never be auto-restored.
pub static KEEP: WordList = list!("keep");
/// English words that contain Telex double patterns.
pub static DOUBLES: WordList = list!("doubles");

impl WordList {
    pub fn len(&self) -> usize {
        self.idx.len() / 4 - 1
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    #[inline]
    fn offset(&self, i: usize) -> usize {
        u32::from_le_bytes([
            self.idx[4 * i],
            self.idx[4 * i + 1],
            self.idx[4 * i + 2],
            self.idx[4 * i + 3],
        ]) as usize
    }

    /// Entry `i` without its trailing newline (UTF-8 bytes: byte order = code point order).
    #[inline]
    fn entry(&self, i: usize) -> &'static [u8] {
        &self.blob[self.offset(i)..self.offset(i + 1) - 1]
    }

    /// The slice of entries that can start with `key`: its pair of first letters picks a bucket.
    #[inline]
    fn bucket(&self, key: &[u8]) -> (usize, usize) {
        if let [a @ b'a'..=b'z', b @ b'a'..=b'z', ..] = *key {
            let k = (a - b'a') as usize * 26 + (b - b'a') as usize;
            let at = |i: usize| {
                u32::from_le_bytes([
                    self.bkt[4 * i],
                    self.bkt[4 * i + 1],
                    self.bkt[4 * i + 2],
                    self.bkt[4 * i + 3],
                ]) as usize
            };
            (at(k), at(k + 1))
        } else {
            (0, self.len())
        }
    }

    fn search(&self, key: &[u8]) -> bool {
        let (mut lo, mut hi) = self.bucket(key);
        while lo < hi {
            let mid = (lo + hi) / 2;
            match self.entry(mid).cmp(key) {
                Ordering::Less => lo = mid + 1,
                Ordering::Greater => hi = mid,
                Ordering::Equal => return true,
            }
        }
        false
    }

    /// Exact match.
    pub fn contains(&self, word: &str) -> bool {
        self.search(word.as_bytes())
    }

    /// Match after lower-casing `word` (entries are compared as stored). The query is lowered
    /// once into a stack buffer, not once per probe.
    pub fn contains_lower(&self, word: &str) -> bool {
        let mut buf = [0u8; 128];
        match lower_into(word, &mut buf) {
            Some(n) => self.search(&buf[..n]),
            None => false, // longer than any entry
        }
    }

    /// Whether some entry starts with `prefix` (lower-cased like `contains_lower`).
    pub fn has_prefix_lower(&self, prefix: &str) -> bool {
        let mut buf = [0u8; 128];
        let Some(n) = lower_into(prefix, &mut buf) else {
            return false;
        };
        let key = &buf[..n];
        // first entry in the bucket that is not smaller than the prefix
        let (mut lo, mut hi) = self.bucket(key);
        let end = hi;
        while lo < hi {
            let mid = (lo + hi) / 2;
            if self.entry(mid) < key {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }
        lo < end && self.entry(lo).starts_with(key)
    }
}

/// `word` lower-cased into `buf`; `None` when it does not fit. ASCII needs no Unicode tables.
#[inline]
fn lower_into(word: &str, buf: &mut [u8; 128]) -> Option<usize> {
    if word.is_ascii() {
        let b = word.as_bytes();
        if b.len() > buf.len() {
            return None;
        }
        for (d, s) in buf.iter_mut().zip(b) {
            *d = s.to_ascii_lowercase();
        }
        return Some(b.len());
    }
    let mut n = 0;
    for c in word.chars() {
        for l in c.to_lowercase() {
            if n + l.len_utf8() > buf.len() {
                return None;
            }
            n += l.encode_utf8(&mut buf[n..]).len();
        }
    }
    Some(n)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lists_are_loaded_and_sorted() {
        assert!(
            EN.len() >= 17_000 && VI.len() >= 6_000 && DOUBLES.len() >= 10_000 && !KEEP.is_empty()
        );
        for list in [&EN, &VI, &KEEP, &DOUBLES] {
            for i in 1..list.len() {
                assert!(list.entry(i - 1) < list.entry(i), "unsorted at {i}");
            }
        }
    }

    #[test]
    fn buckets_agree_with_a_plain_binary_search() {
        for list in [&EN, &VI, &KEEP, &DOUBLES] {
            for i in 0..list.len() {
                let w = std::str::from_utf8(list.entry(i)).unwrap();
                assert!(list.contains(w), "{w} lost by its bucket");
                // every prefix of a stored word is found as a prefix
                let lower = w.to_lowercase();
                if lower == w {
                    for k in 1..=w.len().min(6) {
                        if w.is_char_boundary(k) {
                            assert!(list.has_prefix_lower(&w[..k]), "{w}[..{k}]");
                        }
                    }
                }
            }
            assert!(!list.contains("zzzzqq") && !list.has_prefix_lower("zzzzqq"));
        }
    }

    #[test]
    fn lookups() {
        assert!(EN.contains_lower("The") && EN.contains_lower("VIEW") && !EN.contains_lower("qqq"));
        assert!(
            VI.contains_lower("Chào") && VI.contains_lower("được") && !VI.contains_lower("hello")
        );
        assert!(DOUBLES.contains("aachen") && !DOUBLES.contains("Aachen"));
        assert!(
            EN.has_prefix_lower("Expec")
                && EN.has_prefix_lower("the")
                && !EN.has_prefix_lower("xinc")
        );
    }
}
