//! Static word lists: no initialisation, no heap, no hashing.
//!
//! Generated by build.rs from the dictionary files. A list is a sorted blob plus an offset
//! table; lookup is a binary search that compares in place, lower-casing the query on the fly.
//! (The old `LazyLock<HashSet>` rebuilt 24k entries on the first keystroke and allocated a
//! `String` per lookup.)

use std::cmp::Ordering;

pub struct WordList {
    blob: &'static [u8],
    idx: &'static [u8],
}

macro_rules! list {
    ($name:literal) => {
        WordList {
            blob: include_bytes!(concat!(env!("OUT_DIR"), "/", $name, ".blob")),
            idx: include_bytes!(concat!(env!("OUT_DIR"), "/", $name, ".idx")),
        }
    };
}

/// English words (auto-restore); consulted only at word boundaries by the restore logic.
pub static EN: WordList = list!("en");
/// Vietnamese syllables.
pub static VI: WordList = list!("vi");
/// Words that must never be auto-restored.
pub static KEEP: WordList = list!("keep");
/// English words that contain Telex double patterns.
pub static DOUBLES: WordList = list!("doubles");

impl WordList {
    pub fn len(&self) -> usize {
        self.idx.len() / 4 - 1
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    #[inline]
    fn offset(&self, i: usize) -> usize {
        u32::from_le_bytes([
            self.idx[4 * i],
            self.idx[4 * i + 1],
            self.idx[4 * i + 2],
            self.idx[4 * i + 3],
        ]) as usize
    }

    /// Entry `i` without its trailing newline (UTF-8 bytes: byte order = code point order).
    #[inline]
    fn entry(&self, i: usize) -> &'static [u8] {
        &self.blob[self.offset(i)..self.offset(i + 1) - 1]
    }

    fn search(&self, key: &[u8]) -> bool {
        let (mut lo, mut hi) = (0, self.len());
        while lo < hi {
            let mid = (lo + hi) / 2;
            match self.entry(mid).cmp(key) {
                Ordering::Less => lo = mid + 1,
                Ordering::Greater => hi = mid,
                Ordering::Equal => return true,
            }
        }
        false
    }

    /// Exact match.
    pub fn contains(&self, word: &str) -> bool {
        self.search(word.as_bytes())
    }

    /// Match after lower-casing `word` (entries are compared as stored). The query is lowered
    /// once into a stack buffer, not once per probe.
    pub fn contains_lower(&self, word: &str) -> bool {
        let mut buf = [0u8; 128];
        let mut n = 0;
        for c in word.chars() {
            for l in c.to_lowercase() {
                if n + l.len_utf8() > buf.len() {
                    return false; // longer than any entry
                }
                n += l.encode_utf8(&mut buf[n..]).len();
            }
        }
        self.search(&buf[..n])
    }

    /// Whether some entry starts with `prefix` (lower-cased like `contains_lower`).
    pub fn has_prefix_lower(&self, prefix: &str) -> bool {
        let mut buf = [0u8; 128];
        let mut n = 0;
        for c in prefix.chars() {
            for l in c.to_lowercase() {
                if n + l.len_utf8() > buf.len() {
                    return false;
                }
                n += l.encode_utf8(&mut buf[n..]).len();
            }
        }
        let key = &buf[..n];
        // first entry that is not smaller than the prefix
        let (mut lo, mut hi) = (0, self.len());
        while lo < hi {
            let mid = (lo + hi) / 2;
            if self.entry(mid) < key {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }
        lo < self.len() && self.entry(lo).starts_with(key)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lists_are_loaded_and_sorted() {
        assert!(
            EN.len() >= 17_000 && VI.len() >= 6_000 && DOUBLES.len() >= 10_000 && !KEEP.is_empty()
        );
        for list in [&EN, &VI, &KEEP, &DOUBLES] {
            for i in 1..list.len() {
                assert!(list.entry(i - 1) < list.entry(i), "unsorted at {i}");
            }
        }
    }

    #[test]
    fn lookups() {
        assert!(EN.contains_lower("The") && EN.contains_lower("VIEW") && !EN.contains_lower("qqq"));
        assert!(
            VI.contains_lower("Chào") && VI.contains_lower("được") && !VI.contains_lower("hello")
        );
        assert!(DOUBLES.contains("aachen") && !DOUBLES.contains("Aachen"));
        assert!(
            EN.has_prefix_lower("Expec")
                && EN.has_prefix_lower("the")
                && !EN.has_prefix_lower("xinc")
        );
    }
}
