//! Vietnamese phonology: pure, stateless, allocation-free.
//!
//! Nothing in here knows about keycodes, the typing buffer, dictionaries of English, or the
//! engine. Everything the engine needs to decide "may I transform?" and "where does the tone
//! go?" lives behind these functions, so a rule is written exactly once.

pub mod letters;
// generated by scripts/gen/phonology_tables.py: rustfmt must not rewrite it
#[rustfmt::skip]
pub mod tables;
pub mod tone_place;
pub mod validity;

pub use letters::{Mod, Tone, Unit};
pub use tone_place::tone_index;
pub use validity::{nucleus_len, validate, Opts, Validity};
