// GENERATED by scripts/gen/phonology_tables.py: edit the dictionaries or the script, not this file.
// Source: vi.dic (6676 syllables used, 32 non-syllables excluded), names.dic (5 names).

pub const OPEN: u16 = 1 << 0;
pub const C: u16 = 1 << 1;
pub const CH: u16 = 1 << 2;
pub const M: u16 = 1 << 3;
pub const N: u16 = 1 << 4;
pub const NG: u16 = 1 << 5;
pub const NH: u16 = 1 << 6;
pub const P: u16 = 1 << 7;
pub const T: u16 = 1 << 8;
pub const K: u16 = 1 << 9;
/// Typing-time (lenient) mode also accepts C|M|N|NG|P|T after this nucleus.
pub const WIDE: u16 = 1 << 10;
pub const STOPS: u16 = C | CH | P | T | K;

/// Vowel nucleus -> allowed codas (OPEN = no consonant coda). Nucleus list = docs §7.6 plus attested forms;
/// a nucleus without OPEN must be followed by a coda (iê, uô, ươ...). Letters are pre-decoded:
/// (base letter, modifier) with modifier 0 none, 1 circumflex, 2 horn, 3 breve, 4 stroke.
pub const NUCLEUS_CODAS: &[(&[(u8, u8)], u16)] = &[
    (&[(b'a', 0)], OPEN | C | CH | M | N | NG | NH | P | T), // a -:132 c:45 ch:39 m:74 n:102 ng:104 nh:97 p:33 t:41
    (&[(b'e', 0)], OPEN | C | M | N | NG | P | T), // e -:114 c:12 m:47 n:76 ng:17 p:30 t:40
    (&[(b'i', 0)], OPEN | CH | M | N | NH | P | T), // i -:113 ch:36 m:39 n:38 nh:85 p:16 t:41
    (&[(b'o', 0)], OPEN | C | M | N | NG | P | T), // o -:108 c:43 m:78 n:65 ng:101 p:22 t:40
    (&[(b'u', 0)], OPEN | C | M | N | NG | P | T), // u -:110 c:41 m:62 n:61 ng:94 p:26 t:38
    (&[(b'y', 0)], OPEN | NH | T),                 // y -:22 nh:3 t:2
    (&[(b'a', 1)], C | M | N | NG | P | T),        // â c:15 m:103 n:105 ng:25 p:45 t:38
    (&[(b'e', 1)], OPEN | C | CH | M | N | NG | NH | P | T), // ê -:103 c:1 ch:27 m:19 n:44 ng:3 nh:54 p:11 t:26
    (&[(b'o', 1)], OPEN | C | M | N | NG | P | T), // ô -:112 c:37 m:47 n:74 ng:92 p:25 t:32
    (&[(b'a', 3)], C | M | N | NG | P | T | K),    // ă c:38 m:71 n:86 ng:89 p:24 t:37 k:2
    (&[(b'o', 2)], OPEN | M | N | P | T),          // ơ -:119 m:46 n:63 p:24 t:32
    (&[(b'u', 2)], OPEN | C | M | N | NG | T),     // ư -:78 c:35 m:1 n:2 ng:76 t:18
    (&[(b'a', 0), (b'i', 0)], OPEN),               // ai -:118
    (&[(b'a', 0), (b'o', 0)], OPEN),               // ao -:115
    (&[(b'a', 0), (b'u', 0)], OPEN),               // au -:59
    (&[(b'a', 0), (b'y', 0)], OPEN),               // ay -:92
    (&[(b'e', 0), (b'o', 0)], OPEN),               // eo -:103
    (&[(b'i', 0), (b'a', 0)], OPEN),               // ia -:52
    (&[(b'i', 0), (b'u', 0)], OPEN),               // iu -:54
    (&[(b'i', 0), (b'e', 1)], C | M | N | NG | P | T), // iê c:13 m:45 n:73 ng:37 p:16 t:29
    (
        &[(b'o', 0), (b'a', 0)],
        OPEN | C | CH | M | N | NG | NH | P | T,
    ), // oa -:68 c:10 ch:5 m:5 n:37 ng:41 nh:14 p:2 t:12
    (&[(b'o', 0), (b'e', 0)], OPEN | N | T | WIDE), // oe -:48 n:12 t:13
    (&[(b'o', 0), (b'i', 0)], OPEN),               // oi -:92
    (&[(b'o', 0), (b'o', 0)], C | NG | WIDE),      // oo c:3 ng:10
    (&[(b'o', 0), (b'a', 3)], C | M | N | NG | T), // oă c:4 m:6 n:10 ng:10 t:10
    (&[(b'u', 0), (b'a', 0)], OPEN),               // ua -:54
    (&[(b'u', 0), (b'i', 0)], OPEN),               // ui -:79
    (&[(b'u', 0), (b'y', 0)], OPEN | CH | N | NH | T | WIDE), // uy -:52 ch:3 n:1 nh:7 t:7
    (&[(b'u', 0), (b'a', 1)], N | NG | T | WIDE),  // uâ n:21 ng:1 t:9
    (&[(b'u', 0), (b'e', 1)], OPEN | CH | NH | WIDE), // uê -:19 ch:7 nh:3
    (&[(b'u', 0), (b'o', 1)], C | M | N | NG | T), // uô c:19 m:13 n:22 ng:36 t:17
    (&[(b'u', 0), (b'o', 2)], OPEN | N | WIDE),    // uơ -:4 n:1
    (&[(b'y', 0), (b'e', 1)], M | N | NG | T | WIDE), // yê m:2 n:7 ng:2 t:3
    (&[(b'a', 1), (b'u', 0)], OPEN),               // âu -:89
    (&[(b'a', 1), (b'y', 0)], OPEN),               // ây -:96
    (&[(b'e', 1), (b'u', 0)], OPEN),               // êu -:47
    (&[(b'o', 1), (b'i', 0)], OPEN),               // ôi -:92
    (&[(b'o', 2), (b'i', 0)], OPEN),               // ơi -:65
    (&[(b'u', 2), (b'a', 0)], OPEN),               // ưa -:71
    (&[(b'u', 2), (b'i', 0)], OPEN),               // ưi -:4
    (&[(b'u', 2), (b'u', 0)], OPEN),               // ưu -:23
    (&[(b'u', 2), (b'o', 2)], C | M | N | NG | P | T), // ươ c:26 m:22 n:25 ng:82 p:8 t:17
    (&[(b'i', 0), (b'e', 1), (b'u', 0)], OPEN),    // iêu -:59
    (&[(b'o', 0), (b'a', 0), (b'i', 0)], OPEN),    // oai -:35
    (&[(b'o', 0), (b'a', 0), (b'o', 0)], OPEN),    // oao -:3
    (&[(b'o', 0), (b'a', 0), (b'y', 0)], OPEN),    // oay -:13
    (&[(b'o', 0), (b'e', 0), (b'o', 0)], OPEN),    // oeo -:4
    (&[(b'u', 0), (b'y', 0), (b'a', 0)], OPEN),    // uya -:3
    (&[(b'u', 0), (b'y', 0), (b'u', 0)], OPEN),    // uyu -:3
    (&[(b'u', 0), (b'y', 0), (b'e', 1)], N | T | WIDE), // uyê n:34 t:9
    (&[(b'u', 0), (b'a', 1), (b'y', 0)], OPEN),    // uây -:5
    (&[(b'u', 0), (b'e', 1), (b'u', 0)], OPEN),    // uêu -:0
    (&[(b'u', 0), (b'o', 1), (b'i', 0)], OPEN),    // uôi -:29
    (&[(b'y', 0), (b'e', 1), (b'u', 0)], OPEN),    // yêu -:3
    (&[(b'u', 2), (b'o', 2), (b'i', 0)], OPEN),    // ươi -:29
    (&[(b'u', 2), (b'o', 2), (b'u', 0)], OPEN),    // ươu -:7
];

/// `NUCLEUS_CODAS` flattened for typing time: key = base-25 digits of (letter a e i o u y)*4 + modifier + 1;
/// value = (codas of an exact match, codas when only diacritics are missing, is a proper prefix).
pub const NUCLEUS_INDEX: &[(u16, u16, u16, bool)] = &[
    (1, 511, 954, true),
    (2, 442, 0, true),
    (4, 954, 0, false),
    (5, 443, 511, true),
    (6, 511, 0, true),
    (9, 477, 0, true),
    (13, 443, 443, true),
    (14, 443, 0, true),
    (15, 409, 0, true),
    (17, 443, 315, true),
    (19, 315, 0, true),
    (21, 321, 0, true),
    (34, 1, 0, false),
    (38, 1, 0, false),
    (42, 1, 1, false),
    (46, 1, 1, false),
    (67, 1, 0, false),
    (71, 1, 0, false),
    (138, 1, 0, false),
    (142, 0, 1, false),
    (167, 1, 0, false),
    (226, 1, 0, false),
    (230, 0, 442, true),
    (231, 442, 0, true),
    (242, 1, 0, false),
    (326, 511, 314, true),
    (329, 314, 0, false),
    (330, 1297, 0, true),
    (334, 1, 1, false),
    (338, 1058, 0, false),
    (359, 1, 0, false),
    (384, 1, 0, false),
    (426, 1, 1329, true),
    (427, 1328, 0, true),
    (430, 0, 1093, true),
    (431, 1093, 0, true),
    (434, 1, 1, false),
    (438, 0, 1467, true),
    (439, 314, 0, true),
    (440, 1041, 442, true),
    (442, 0, 1, false),
    (446, 1365, 0, true),
    (476, 1, 0, false),
    (484, 1, 0, false),
    (488, 0, 442, true),
    (490, 442, 0, true),
    (492, 1, 0, false),
    (530, 0, 1336, true),
    (531, 1336, 0, true),
    (5767, 0, 1, false),
    (5792, 1, 0, false),
    (8159, 1, 0, false),
    (8163, 1, 0, false),
    (8171, 1, 0, false),
    (8263, 1, 0, false),
    (10671, 0, 1, false),
    (10696, 1, 0, false),
    (10767, 0, 1, false),
    (10792, 1, 0, false),
    (10959, 0, 1, false),
    (10967, 0, 1, false),
    (10984, 1, 0, false),
    (11009, 0, 1, false),
    (11017, 0, 1, false),
    (11151, 1, 0, false),
    (11155, 0, 1296, false),
    (11156, 1296, 0, false),
    (11167, 1, 0, false),
    (12209, 0, 1, false),
    (12217, 0, 1, false),
    (12259, 1, 0, false),
    (12267, 1, 0, false),
    (13267, 0, 1, false),
    (13292, 1, 0, false),
];

/// Proper-name syllables whose spelling breaks the regular rules (data, prefix-closed at match time).
/// (letters as above, tone 0 ngang 1 sắc 2 huyền 3 hỏi 4 ngã 5 nặng)
pub const NAMES: &[(&[(u8, u8)], u8)] = &[
    (&[(b'k', 0), (b'a', 0), (b'n', 0)], 5),            // kạn
    (&[(b'k', 0), (b'o', 1), (b'n', 0), (b'g', 0)], 0), // kông
    (&[(b'k', 0), (b'o', 0), (b'n', 0)], 0),            // kon
    (&[(b'k', 0), (b'r', 0), (b'o', 1), (b'n', 0), (b'g', 0)], 0), // krông
    (&[(b'b', 0), (b'u', 0), (b'k', 0)], 1),            // búk
];
